version: 2
updates:
- package-ecosystem: cargo
  directory: "/ababot"
  schedule:
    interval: "weekly"
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "semver"
    - dependency-name: "crates-io"
      update-types: ["version-update:semver-patch"]
