[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dir_macros = { path = "../dir_macros" }
serenity = "0.11"
tracing = "0.1"
tokio = { version = "1", features =  ["full"] }