# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate project
    runs-on: ubuntu-latest
    environment: testing
    defaults:
      run:
        working-directory: ./ababot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with: 
          workspaces: "./ababot -> target"
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Validate
        run: cargo check

  test:
    name: Test project
    runs-on: ubuntu-latest
    environment: publishing
    needs: [validate]
    defaults:
      run:
        working-directory: ./ababot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        run: cargo test